Method of Least Square

In [1]:
import numpy as np

In [5]:
x= np.array([2,5,7,8,9,10,23,45])
y= np.array([13,15,20,34,36,56,66,78])

In [7]:
xi = x.sum()

In [9]:
xi

109

In [11]:
yi = y.sum()

In [13]:
yi

318

In [15]:
xisqr = xi**2

In [21]:
n=8

In [23]:
xisqrn = xisqr/n

In [25]:
xsqr = x **2

In [31]:
xsqr

array([   4,   25,   49,   64,   81,  100,  529, 2025])

In [29]:
xsqrs = xsqr.sum()

In [33]:
xsqrs

2877

In [35]:
xiyi = x*y

In [37]:
num = (xi*yi)/n - xiyi

In [39]:
num

array([4306.75, 4257.75, 4192.75, 4060.75, 4008.75, 3772.75, 2814.75,
        822.75])

In [41]:
den = xisqrn - xisqr

In [47]:
b1 = num/den

In [49]:
b1

array([-0.41427489, -0.40956148, -0.403309  , -0.39061166, -0.38560968,
       -0.36290837, -0.27075643, -0.07914197])

In [51]:
s_x = np.sum(x)
s_y = np.sum(y)
s_xy= np.sum(x*y) #np.dot(x,y)
s_xx= np.sum(x*x)
n= len(x)

In [55]:
num_b1 = s_x*s_y/n - s_xy
den_b1 = (s_x**2)/n - s_xx
b1= num_b1/den_b1
b1

1.5031881454872025

In [53]:
b1 = ((s_x*s_y/n) - s_xy)/((s_x**2/n) - s_xx)
b1

1.5031881454872025

In [61]:
b0= (s_y-b1*s_x)/n
b0

19.269061517736866

In [67]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
x

array([ 2,  5,  7,  8,  9, 10, 23, 45])

In [75]:
lr.fit(x.reshape(-1,1),y)
lr.intercept_, lr.coef_

(19.26906151773686, array([1.50318815]))

In [77]:
x

array([ 2,  5,  7,  8,  9, 10, 23, 45])