In [50]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression,ElasticNet
from sklearn.metrics import r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.model_selection import KFold, cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [51]:
iris= pd.read_csv("Iris.csv")

In [52]:
iris.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [53]:
lbl= LabelEncoder()
iris['Species']= lbl.fit_transform(iris['Species'])

In [54]:
lbl.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [55]:
y= iris['Species']
X = iris.drop('Species', axis=1)

In [56]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [57]:
y.unique()

array([0, 1, 2])

In [58]:
X.isnull().sum().sum()

0

In [59]:
y.value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [60]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=24,test_size=0.3)

In [61]:
lr= LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [62]:
print (confusion_matrix(y_test, y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 18]]


In [63]:
accuracy_score(y_test, y_pred)

0.9777777777777777

In [64]:
y.value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

Naive Rule/ Baseline Model

In [65]:
y_pred= np.repeat(2,y_test.shape[0])

In [66]:
y_test. value_counts()

Species
2    18
0    15
1    12
Name: count, dtype: int64

In [67]:
accuracy_score(y_test,y_pred)

0.4