In [2]:
from sklearn.ensemble import IsolationForest
from sklearn.cluster import KMeans

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler


In [5]:
milk= pd.read_csv("milk.csv", index_col=0)
iso= IsolationForest(random_state=24, n_estimators=25, contamination=0.05)
iso.fit_predict(milk)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1])

In [20]:
df_clust = pd.DataFrame({'animal':list(milk.index),
                         'predict': list(iso.fit_predict(milk))})

In [21]:
df_clust

animal  predict
0        HORSE        1
1    ORANGUTAN        1
2       MONKEY        1
3       DONKEY        1
4        HIPPO        1
5        CAMEL        1
6        BISON        1
7      BUFFALO        1
8   GUINEA PIG        1
9          CAT        1
10         FOX        1
11       LLAMA        1
12        MULE        1
13         PIG        1
14       ZEBRA        1
15       SHEEP        1
16         DOG        1
17    ELEPHANT        1
18      RABBIT        1
19         RAT        1
20        DEER        1
21    REINDEER        1
22       WHALE        1
23        SEAL       -1
24     DOLPHIN       -1

In [9]:
### RFM dataset

In [10]:
rfm= pd.read_csv("rfm_data_customer.csv", index_col=0)
rfm.drop('most_recent_visit', inplace=True, axis=1)

In [14]:
iso= IsolationForest(random_state=24, n_estimators=25, contamination=0.05)
labels=iso.fit_predict(rfm)

In [15]:
rfm

revenue  number_of_orders  recency_days
customer_id                                         
22086            777                 9           232
2290            1555                16           115
26377            336                 5            43
24650           1189                12            64
12883           1229                12            23
...              ...               ...           ...
3249             998                10            31
6686             771                 8           187
16418           1016                 9           154
9117             678                 7           195
19184           1519                13           113

[39999 rows x 3 columns]

In [16]:
np.unique(labels, return_counts=True)

(array([-1,  1]), array([ 2000, 37999], dtype=int64))

In [26]:
iso= IsolationForest(random_state=24, n_estimators=100, contamination=0.1)
iso.fit_predict(rfm)

array([ 1,  1, -1, ...,  1,  1,  1])