In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge 

In [16]:
from ucimlrepo import fetch_ucirepo 

concrete_compressive_strength = fetch_ucirepo(id=165)   

X = concrete_compressive_strength.data.features 
y = concrete_compressive_strength.data.targets 


In [17]:
# X_train, X_test,y_train,y_test = train_test_split(X,y,random_state=24,test_size=0.3)

In [18]:
lr = LinearRegression()

In [19]:
lr.fit(X,y)

LinearRegression()

In [20]:
lr.intercept_

array([-23.33121358])

In [21]:
ridge = Ridge()

In [22]:
ridge.fit(X,y)

Ridge()

In [24]:
ridge.intercept_

array([-23.32957301])

In [25]:
X_train, X_test,y_train,y_test = train_test_split(X,y,random_state=24,test_size=0.3)

In [26]:
ridge.fit(X_train,y_train)

Ridge()

In [27]:
y_pred =ridge.predict(X_test)

In [28]:
r2_score(y_test,y_pred)

0.5771749099675626

In [29]:
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
y_pred =lr.predict(X_test)
r2_score(y_test,y_pred)

0.5771752777048791

In [44]:
#ridge and polynomial

In [45]:
poly = PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly_trn = poly.fit_transform(X_train)
X_poly_tst = poly.transform(X_test)

In [50]:
X_train

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
538   480.0                 0.0      0.0  192.0               0.0   
434   178.0               129.8    118.6  179.9               3.6   
454   250.0                 0.0     95.7  191.8               5.3   
804   393.0                 0.0      0.0  192.0               0.0   
518   202.0                11.0    141.0  206.0               1.7   
..      ...                 ...      ...    ...               ...   
145   469.0               117.2      0.0  137.8              32.2   
343   297.2                 0.0    117.5  174.8               9.5   
192   233.8                 0.0     94.6  197.9               4.6   
899   145.0                 0.0    134.0  181.0              11.0   
418   251.4                 0.0    118.3  192.9               5.8   

     Coarse Aggregate  Fine Aggregate  Age  
538             936.2           712.2    7  
434            1007.3           746.8   28  
454             948.9           857.2   56  
804             940.0           758.0   28  
518             942.0           801.0   56  
..                ...             ...  ...  
145             852.1           840.5   56  
343            1022.8           753.5  100  
192             947.0           852.2   56  
899             979.0           812.0   28  
418            1043.6           754.3    3  

[721 rows x 8 columns]

In [51]:
X_poly_trn

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
538   480.0                 0.0      0.0  192.0               0.0   
434   178.0               129.8    118.6  179.9               3.6   
454   250.0                 0.0     95.7  191.8               5.3   
804   393.0                 0.0      0.0  192.0               0.0   
518   202.0                11.0    141.0  206.0               1.7   
..      ...                 ...      ...    ...               ...   
145   469.0               117.2      0.0  137.8              32.2   
343   297.2                 0.0    117.5  174.8               9.5   
192   233.8                 0.0     94.6  197.9               4.6   
899   145.0                 0.0    134.0  181.0              11.0   
418   251.4                 0.0    118.3  192.9               5.8   

     Coarse Aggregate  Fine Aggregate    Age   Cement^2  \
538             936.2           712.2    7.0  230400.00   
434            1007.3           746.8   28.0   31684.00   
454             948.9           857.2   56.0   62500.00   
804             940.0           758.0   28.0  154449.00   
518             942.0           801.0   56.0   40804.00   
..                ...             ...    ...        ...   
145             852.1           840.5   56.0  219961.00   
343            1022.8           753.5  100.0   88327.84   
192             947.0           852.2   56.0   54662.44   
899             979.0           812.0   28.0   21025.00   
418            1043.6           754.3    3.0   63201.96   

     Cement Blast Furnace Slag  ...  Coarse Aggregate^3  \
538                        0.0  ...        8.205516e+08   
434                    23104.4  ...        1.022060e+09   
454                        0.0  ...        8.544002e+08   
804                        0.0  ...        8.305840e+08   
518                     2222.0  ...        8.358969e+08   
..                         ...  ...                 ...   
145                    54966.8  ...        6.186880e+08   
343                        0.0  ...        1.069971e+09   
192                        0.0  ...        8.492781e+08   
899                        0.0  ...        9.383137e+08   
418                        0.0  ...        1.136586e+09   

     Coarse Aggregate^2 Fine Aggregate  Coarse Aggregate^2 Age  \
538                       6.242222e+08            6.135293e+06   
434                       7.577431e+08            2.841029e+07   
454                       7.718325e+08            5.042303e+07   
804                       6.697688e+08            2.474080e+07   
518                       7.107786e+08            4.969238e+07   
..                                 ...                     ...   
145                       6.102655e+08            4.066017e+07   
343                       7.882513e+08            1.046120e+08   
192                       7.642606e+08            5.022130e+07   
899                       7.782541e+08            2.683635e+07   
418                       8.215089e+08            3.267303e+06   

     Coarse Aggregate Fine Aggregate^2  Coarse Aggregate Fine Aggregate Age  \
538                       4.748676e+08                           4667331.48   
434                       5.617815e+08                          21063045.92   
454                       6.972440e+08                          45550236.48   
804                       5.400902e+08                          19950560.00   
518                       6.043881e+08                          42254352.00   
..                                 ...                                  ...   
145                       6.019577e+08                          40106642.80   
343                       5.807072e+08                          77067980.00   
192                       6.877539e+08                          45193870.40   
899                       6.454978e+08                          22258544.00   
418                       5.937755e+08                           2361562.44   

     Coarse Aggr

In [46]:
ridge.fit(X_poly_trn,y_train)
y_pred = ridge.predict(X_poly_tst)

C:\anaconda-install\Lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=9.96075e-21): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


In [43]:
r2_score(y_test,y_pred)

0.8695065063191985

In [47]:
ridge.coef_

array([[-2.71369370e+00,  6.36143557e-01, -2.19104687e+00,
        -1.48949528e-01, -3.22459488e-02,  2.61227210e+00,
         9.09094082e-01,  1.23618480e-01,  1.04451224e-02,
         3.12236342e-02,  8.66605537e-03, -1.73567888e-02,
        -7.42857148e-02, -1.64249699e-02,  2.33994125e-02,
        -4.52764597e-03,  4.92733932e-03,  1.51316208e-02,
         1.13976755e-02,  1.08260044e-01, -4.35844961e-02,
         4.03424911e-02,  1.65439810e-02, -3.37890818e-02,
         2.12356041e-02,  2.88636317e-01, -3.78369592e-02,
         5.09089174e-02, -5.32041881e-03, -2.30583708e-02,
        -1.11741016e+00,  2.00777909e-02,  1.04069153e-02,
         1.60386889e-02, -3.23959572e-01,  3.57926884e-01,
        -2.09066877e-01,  6.01483221e-01,  4.92214122e-03,
        -1.11664061e-02, -1.04666932e-02, -3.84180728e-04,
         1.05299930e-02,  1.60574796e-03, -1.64009969e-06,
        -8.64560240e-06, -3.67881935e-06, -1.01479370e-05,
        -2.68947401e-05,  1.96601616e-07, -8.83725261e-0

In [48]:
df = pd.DataFrame({'cols': list(X_poly_trn.columns),
                    'coeff':list(ridge.coef_[0])})

In [49]:
df[df['coeff'] > 0.0001]

cols     coeff
1                           Blast Furnace Slag  0.636144
5                             Coarse Aggregate  2.612272
6                               Fine Aggregate  0.909094
7                                          Age  0.123618
8                                     Cement^2  0.010445
9                    Cement Blast Furnace Slag  0.031224
10                              Cement Fly Ash  0.008666
14                       Cement Fine Aggregate  0.023399
16                        Blast Furnace Slag^2  0.004927
17                  Blast Furnace Slag Fly Ash  0.015132
18                    Blast Furnace Slag Water  0.011398
19         Blast Furnace Slag Superplasticizer  0.108260
21           Blast Furnace Slag Fine Aggregate  0.040342
22                      Blast Furnace Slag Age  0.016544
24                               Fly Ash Water  0.021236
25                    Fly Ash Superplasticizer  0.288636
27                      Fly Ash Fine Aggregate  0.050909
31                      Water Coarse Aggregate  0.020078
32                        Water Fine Aggregate  0.010407
33                                   Water Age  0.016039
35           Superplasticizer Coarse Aggregate  0.357927
37                        Superplasticizer Age  0.601483
38                          Coarse Aggregate^2  0.004922
42                          Fine Aggregate Age  0.010530
43                                       Age^2  0.001606
66               Cement Water Superplasticizer  0.000638
70                   Cement Superplasticizer^2  0.000930
94   Blast Furnace Slag Water Superplasticizer  0.000233
98       Blast Furnace Slag Superplasticizer^2  0.000221
115             Fly Ash Water Superplasticizer  0.000591
119                 Fly Ash Superplasticizer^2  0.001580
130                   Water^2 Superplasticizer  0.001146
136      Water Superplasticizer Fine Aggregate  0.000637
146          Superplasticizer^2 Fine Aggregate  0.000393
147                     Superplasticizer^2 Age  0.000688

In [52]:
#Considrring different cvalues for alpha

In [61]:
ridge = Ridge(alpha=1)
ridge.fit(X_train,y_train)
y_pred = ridge.predict(X_test)
r2_score(y_test,y_pred)

0.5771749099675626

#Tuning for alpha values = [0.01,0.1,0.3,0.6,1,1.5,2,4,10]
Hyperparameter tuning
parameter optiimization

In [76]:
alphas =  [0.01,0.1,0.3,0.6,1,1.5,2,4,10]
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred = ridge.predict(X_test)
    scores.append(r2_score(y_test,y_pred))
    

In [77]:
scores


[0.5771752740273375,
 0.5771752409296147,
 0.5771751673801079,
 0.5771750570584018,
 0.5771749099675626,
 0.5771747261116779,
 0.5771745422643093,
 0.5771738069600134,
 0.5771716018651836]

In [78]:
np.max(scores)

0.5771752740273375

In [79]:
i_max = np.argmax(np.max(scores))

In [75]:
print("Best alpha" , alphas[i_max])

Best alpha 0.01


In [80]:
print("Best Scores :",scores[i_max])

Best Scores : 0.5771752740273375


In [81]:
alphas =  np.linspace(0.0001,10,20)
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred = ridge.predict(X_test)
    scores.append(r2_score(y_test,y_pred))
    

In [82]:
np.max(scores)

0.5771752776681036

In [83]:
np.max(scores)

0.5771752776681036

In [84]:
i_max = np.argmax(np.max(scores))

In [85]:
print("Best alpha" , alphas[i_max])

Best alpha 0.0001


In [86]:
print("Best Scores :",scores[i_max])

Best Scores : 0.5771752776681036
