In [22]:
import numpy as np
import pandas as pd


In [23]:
a = np.array([90,34,89,23,50,120,67])

In [24]:
b = np.array([1,3,4,2,5,2,3])

In [25]:
np.mean(a)

67.57142857142857

In [26]:
np.mean(b)

2.857142857142857

In [27]:
ma, mb =np.mean(a),np.mean(b)

In [28]:
ma, mb


(67.57142857142857, 2.857142857142857)

In [29]:
sa, sb = np.std(a),np.std(b)

In [30]:
sa,sb

(31.923377653630677, 1.2453996981544782)

In [31]:
scl_a = (a - ma)/sa

In [32]:
scl_b = (b- mb)/sb

In [33]:
scl_a

array([ 0.70257514, -1.05162521,  0.67125013, -1.39620027, -0.55042511,
        1.64232532, -0.0179    ])

In [34]:
(ma,sa),(scl_a.mean(),scl_a.std())

((67.57142857142857, 31.923377653630677), (7.335402126987641e-17, 1.0))

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scl_std = StandardScaler()

In [38]:
df  = pd.DataFrame({'a':a, 'b':b})

In [39]:
df

a  b
0   90  1
1   34  3
2   89  4
3   23  2
4   50  5
5  120  2
6   67  3

In [46]:
scl_std.fit(df)

StandardScaler()

In [48]:
scl_std.mean_

array([67.57142857,  2.85714286])

In [52]:
np.sqrt(scl_std.var_)  #std

array([31.92337765,  1.2453997 ])

In [53]:
#std
scl_std.scale_

array([31.92337765,  1.2453997 ])

In [54]:
#Min max scaling

(StandardScaler(), array([1, 3, 4, 2, 5, 2, 3]))

In [56]:
a = np.array([90,34,89,23,50,120,67])

In [57]:
b = np.array([1,3,4,2,5,2,3])

In [58]:
mn_a,mn_b,mx_a,mx_b = a.min(),b.min(),a.max(),b.max()

In [59]:
mn_a,mn_b,mx_a,mx_b

(23, 1, 120, 5)

In [60]:
scl_a = (a - mn_a)/(mx_a-mn_a)

In [61]:
scl_a

array([0.69072165, 0.11340206, 0.68041237, 0.        , 0.27835052,
       1.        , 0.45360825])